ArgocdApplications:

  #=================================#
  #      Platform Core Apps         #
  #=================================#

  argocd-image-updater:
    enabled: false

  raw:
    enabled: true

  backstage:
    enabled: false

  team-setup:
    enabled: false

  rancher:
    enabled: false

  vcluster:
    enabled: false

  gitea:
    enabled: false

  tekton-operator:
    enabled: false

  tekton-pipelines:
    enabled: false

  keda:
    enabled: false

  #=================================#
  #          Data Services          #
  #=================================#

  database:
    enabled: true

  postgres-operator:
    enabled: true

  pgadmin:
    enabled: false

  redis:
    enabled: false

  minio:
    enabled: false

  object-storage:
    enabled: false

  #=================================#
  #      Network Services           #
  #=================================#

  metallb:
    enabled: true
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle

  external-dns:
    enabled: true

  ingress-nginx-internal:
    enabled: false

  ingress-nginx-external:
    enabled: true

  cilium:
    enabled: true
    ignoreDifferences:
      - group: "*"
        kind: "*"
        jsonPointers:
        - /spec/template/spec/securityContext/appArmorProfile
  #=================================#
  #      Security & Auth            #
  #=================================#

  keycloak:
    enabled: true
    syncWave: 2 # depends on pg db

  keycloak-operator:
    enabled: true

  cert-manager:
    enabled: true

  sealed-secrets:
    enabled: false

  oauth2-proxy:
    enabled: false
    syncWave: 3 # depends on keycloak

  external-secrets:
    enabled: false

  kyverno:
    enabled: false

  policy:
    enabled: false

  neuvector:
    enabled: false

  vault:
    enabled: false

  vault-secrets-operator:
    enabled: false
    namespace: vault

  secrets:
    enabled: false

  #=================================#
  #      Monitoring Stack           #
  #=================================#

  dashboards:
    enabled: true

  metrics-server:
    enabled: false

  kube-prometheus-stack:
    enabled: true

  kube-prometheus-stack-crds:
    enabled: true
    syncWave: 0 # crds are always first

  loki:
    enabled: true

  promtail:
    enabled: true

  opencost:
    enabled: false

  #=================================#
  #           AI Tools              #
  #=================================#

  ollama:
    enabled: false

  k8sgpt:
    enabled: false
