loki-distributed:
  ingester:
    persistence:
      enabled: true

  querier:
    persistence:
      enabled: true

  compactor:
    persistence:
      enabled: true

  loki:
    structuredConfig:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h # 7 days retention
  gateway:
    ingress:
      enabled: true
      ingressClassName: nginx-external
      hosts:
        - host: loki-gateway.shared.kuberise.dev
          paths:
            - path: /
      tls:
        - hosts:
            - loki-gateway.shared.kuberise.dev
