apiVersion: v1
kind: Service
metadata:
  name: loki-loki-distributed-gateway
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-distributed
  type: ClusterIP
