cilium:
  k8sServiceHost: 192.168.58.4
  k8sServicePort: "6443"
  kubeProxyReplacement: "false"
  bpf:
    masquerade: true
  ipam:
    mode: kubernetes
  operator:
    replicas: 1
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: true
        className: nginx-external
        hosts:
          - hubble.shared.kuberise.dev
